### ISSUE TITLE
Private Video not in recovery.

### ISSUE THREAD

**Issue by nateranney96** [ninsky/recovermyvideotracker#40] opened 2021-03-06 10:35 UTC
So I'm a stickler for my playlist. It's pretty big. this one's been trouble. the usual tricks haven't worked. https://www.youtube.com/watch?v=FFsKlTDk_UU

**Comment by ninsky** [comment] 2021-03-07 20:50
Hello 

If this video was set to private before you've signed up on recovermy.video, such videos can't be recovered. Could this be the reason of your issue?

BR
Nino

**Comment by nateranney96** [comment] 2021-03-07 21:04
I don't think so. It was relatively new to the playlist, and i'ddouble checked when Recover refreshed.

Sent from Yahoo Mail on Android 
 
  On Sun, Mar 7, 2021 at 2:50 PM, Tonino Romano<notifications@github.com> wrote:   


Hello

If this video was set to private before you've signed up on recovermy.video, such videos can't be recovered. Could this be the reason of your issue?

BR
Nino

**Comment by ninsky** [comment] 2021-03-16 08:45
I have to close this issue as it's not reproducible and I couldn't find any other reports about this. Just reopen it in case you have another example which would be reproducible. Thanks anyway!

**Closed as completed by ninsky** 2021-03-16 08:45 UTC
